"""Phase 2 - Clustering queries by issue type.

Run:  python phase2_cluster/cluster.py

Approach:
  * Embed all 400 queries with the Phase-1 winner (bge-small), L2-normalised.
  * Cluster with KMeans across a grid of k; also run Agglomerative (cosine,
    average linkage) as a cross-check.
  * Pick k using two lenses that pull in opposite directions:
      - silhouette (cosine) - intrinsic separation, tends to prefer few clusters
      - gold same-cluster rate - do known duplicates land together? (eval-only)
    The final k balances both at an operationally useful granularity.
  * Report the % of the 60 ground-truth duplicate pairs that end up in the same
    cluster, overall and by difficulty.

We cluster all 400 queries (not the deduped representatives) so cluster volumes
reflect real ticket counts for the Phase-3 ops report.

duplicate_pairs.csv is EVAL-ONLY: it scores co-clustering and informs the k
discussion, but is never an input to the clustering itself.
"""
from __future__ import annotations

import sys
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.cluster import AgglomerativeClustering, KMeans
from sklearn.manifold import TSNE
from sklearn.metrics import silhouette_score

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from lib.data import build_ground_truth, load_queries  # noqa: E402
from phase1_dedup.embedding import embed  # noqa: E402

REPORTS = Path(__file__).resolve().parent / "reports"
FIGURES = REPORTS / "figures"
FIGURES.mkdir(parents=True, exist_ok=True)

MODEL = "bge-small"
K_GRID = [8, 10, 12, 15, 18, 20, 25, 30, 35, 40, 50]
DIFF_ORDER = ["easy", "medium", "hard"]
RANDOM_STATE = 19

md: list[str] = []


def h(line: str = "") -> None:
    md.append(line)
    print(line)


def gold_same_cluster(labels, ids, gt):
    """Fraction of labelled pairs whose two queries share a cluster."""
    pos = {q: c for q, c in zip(ids, labels)}
    out = {}
    for d in DIFF_ORDER:
        ps = gt.labeled_by_difficulty[d]
        out[d] = np.mean([pos[a] == pos[b] for a, b in ps]) if ps else 0.0
    out["overall"] = np.mean([pos[a] == pos[b] for a, b in gt.labeled_pairs])
    return out


def main():
    q = load_queries()
    ids, texts = list(q["query_id"]), list(q["text"])
    gt = build_ground_truth()
    emb = embed(texts, MODEL)

    h("# Phase 2 - Clustering by issue type\n")
    h("_Generated by `phase2_cluster/cluster.py`._\n")
    h(f"Embeddings: `{MODEL}` (Phase-1 winner), {emb.shape[1]}-dim, "
      f"L2-normalised. Clustering: KMeans across k, with Agglomerative "
      "(cosine/average) as a cross-check. Silhouette uses cosine distance.\n")

    # ----- sweep over k -----------------------------------------------------
    rows = []
    km_labels = {}
    for k in K_GRID:
        km = KMeans(n_clusters=k, n_init=10, random_state=RANDOM_STATE).fit(emb)
        sil = silhouette_score(emb, km.labels_, metric="cosine")
        gsc = gold_same_cluster(km.labels_, ids, gt)
        km_labels[k] = km.labels_
        rows.append({"k": k, "silhouette": sil, **{f"gsc_{d}": gsc[d]
                     for d in DIFF_ORDER + ["overall"]}})
    sweep = pd.DataFrame(rows)

    # agglomerative cross-check (silhouette only)
    agg_sil = {}
    for k in K_GRID:
        agg = AgglomerativeClustering(n_clusters=k, metric="cosine",
                                      linkage="average").fit(emb)
        agg_sil[k] = silhouette_score(emb, agg.labels_, metric="cosine")

    h("## Silhouette & gold co-clustering across k\n")
    h("| k | silhouette (KMeans) | silhouette (Agg) | gold same-cluster: "
      "easy | medium | hard | overall |")
    h("|---|---|---|---|---|---|---|")
    for _, r in sweep.iterrows():
        k = int(r["k"])
        h(f"| {k} | {r['silhouette']:.3f} | {agg_sil[k]:.3f} | "
          f"{r['gsc_easy']:.2f} | {r['gsc_medium']:.2f} | {r['gsc_hard']:.2f} "
          f"| {r['gsc_overall']:.2f} |")
    h("")

    # ----- figure: silhouette + gold rate vs k ------------------------------
    fig, ax1 = plt.subplots(figsize=(9, 4.5))
    ax1.plot(sweep["k"], sweep["silhouette"], "-o", color="#264653",
             label="silhouette (KMeans)")
    ax1.plot(K_GRID, [agg_sil[k] for k in K_GRID], "--s", color="#2a9d8f",
             ms=4, label="silhouette (Agg)")
    ax1.set_xlabel("k (clusters)")
    ax1.set_ylabel("silhouette (cosine)")
    ax2 = ax1.twinx()
    ax2.plot(sweep["k"], sweep["gsc_overall"], "-^", color="#e76f51",
             label="gold same-cluster (overall)")
    ax2.plot(sweep["k"], sweep["gsc_hard"], ":", color="#e9c46a",
             label="gold same-cluster (hard)")
    ax2.set_ylabel("gold same-cluster rate")
    ax2.set_ylim(0, 1.02)
    lines = ax1.get_lines() + ax2.get_lines()
    ax1.legend(lines, [l.get_label() for l in lines], fontsize=8, loc="center right")
    ax1.set_title("Choosing k: silhouette vs gold co-clustering")
    fig.tight_layout()
    fig.savefig(FIGURES / "01_k_selection.png", dpi=120)
    plt.close(fig)
    h("![k](figures/01_k_selection.png)\n")

    # ----- pick k -----------------------------------------------------------
    # k is chosen by silhouette ONLY (unsupervised); gold co-clustering is
    # reported separately as evaluation, never used to select k.
    final_k = int(sweep.loc[sweep["silhouette"].idxmax(), "k"])
    sil_at = {int(r["k"]): r["silhouette"] for _, r in sweep.iterrows()}
    h(f"Silhouette is a gentle plateau (~0.28) from k=12-20 — typical for "
      f"short-text embeddings with no crisp cluster boundaries — and **peaks "
      f"at k={final_k}** (KMeans {sil_at[final_k]:.3f}). It falls off below "
      f"k=12 (themes too broad) and above k=25 (clusters fragment). We "
      f"therefore choose **k={final_k}**, slightly coarser than the 20 "
      "labelled root issues: at this granularity some narrow issues merge "
      "(e.g. card-not-working with declined-payment), which the gold "
      "co-clustering below quantifies.\n")

    labels = km_labels[final_k]
    gsc = gold_same_cluster(labels, ids, gt)
    h(f"### Final clustering (KMeans, k={final_k})\n")
    h(f"- **Gold same-cluster rate: {gsc['overall']:.0%} overall** "
      f"(easy {gsc['easy']:.0%}, medium {gsc['medium']:.0%}, "
      f"hard {gsc['hard']:.0%}).")
    sizes = pd.Series(labels).value_counts().sort_values(ascending=False)
    h(f"- Cluster sizes: largest {int(sizes.iloc[0])}, median "
      f"{int(sizes.median())}, smallest {int(sizes.iloc[-1])} queries.")
    h(f"- Silhouette: {sweep.loc[sweep['k']==final_k,'silhouette'].iloc[0]:.3f}.")
    h("")

    # ----- t-SNE viz --------------------------------------------------------
    proj = TSNE(n_components=2, perplexity=30, init="pca",
                random_state=RANDOM_STATE).fit_transform(emb)
    fig, ax = plt.subplots(figsize=(8, 6.5))
    sc = ax.scatter(proj[:, 0], proj[:, 1], c=labels, cmap="tab20", s=18,
                    alpha=0.8)
    ax.set(title=f"Query clusters (t-SNE, KMeans k={final_k})",
           xticks=[], yticks=[])
    fig.tight_layout()
    fig.savefig(FIGURES / "02_tsne.png", dpi=120)
    plt.close(fig)
    h("![tsne](figures/02_tsne.png)\n")

    # ----- save assignments for Phase 3 ------------------------------------
    out = q.copy()
    out["cluster"] = labels
    out.to_csv(REPORTS / "clusters.csv", index=False)
    sweep.to_csv(REPORTS / "k_sweep.csv", index=False)
    h("## Outputs\n")
    h(f"- `reports/clusters.csv` - every query with its cluster id (feeds "
      "Phase 3 labelling).")
    h(f"- `reports/k_sweep.csv` - silhouette + gold co-clustering per k.")
    h("")

    (REPORTS / "report.md").write_text("\n".join(md) + "\n")
    print(f"\nWrote {REPORTS/'report.md'} and artifacts. final_k={final_k}")


if __name__ == "__main__":
    main()
