"""Phase 3 - LLM cluster labelling + weekly ops report.

Run:  python phase3_label/label.py            # offline stub (no key needed)
      ANTHROPIC_API_KEY=... python phase3_label/label.py   # real labels
      Q19_LLM_MODEL=claude-haiku-4-5 ANTHROPIC_API_KEY=... python ...  # cheaper

LLM budget: one call per cluster to label it + one call for the ops report
= k+1 calls total. Representative queries (cluster medoids) are sent, not whole
clusters, to keep prompts small. All calls are cached on disk and cost is
computed from real token usage.
"""
from __future__ import annotations

import sys
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from lib.llm import LLM  # noqa: E402
from lib.text import tokens  # noqa: E402
from phase1_dedup.embedding import embed  # noqa: E402

CLUSTERS_CSV = ROOT / "phase2_cluster" / "reports" / "clusters.csv"
REPORTS = Path(__file__).resolve().parent / "reports"
REPORTS.mkdir(parents=True, exist_ok=True)
MODEL = "bge-small"
N_REPR = 8  # representative queries per cluster sent to the LLM

LABEL_SCHEMA = {
    "type": "object",
    "properties": {
        "label": {"type": "string", "description": "2-4 word issue name"},
        "description": {"type": "string", "description": "one sentence"},
        "severity": {"type": "string", "enum": ["low", "medium", "high"]},
        "needs_escalation": {"type": "boolean"},
    },
    "required": ["label", "description", "severity", "needs_escalation"],
    "additionalProperties": False,
}

md: list[str] = []


def h(line: str = "") -> None:
    md.append(line)
    print(line)


def representatives(texts, emb, idxs):
    """Medoids: queries closest to the cluster centroid."""
    sub = emb[idxs]
    centroid = sub.mean(axis=0)
    centroid /= np.linalg.norm(centroid) + 1e-9
    order = np.argsort(-(sub @ centroid))
    return [texts[idxs[i]] for i in order[:N_REPR]]


def top_terms(texts) -> str:
    c = Counter()
    for t in texts:
        c.update({w for w in tokens(t) if len(w) > 2})
    return ", ".join(w for w, _ in c.most_common(4))


def main():
    df = pd.read_csv(CLUSTERS_CSV, dtype={"query_id": str, "text": str})
    df["cluster"] = df["cluster"].astype(int)
    texts = list(df["text"])
    emb = embed(texts, MODEL)

    llm = LLM()
    mode = "OFFLINE STUB" if llm.offline else f"LIVE ({llm.model})"
    h("# Phase 3 - Cluster labelling & weekly ops report\n")
    h(f"_Generated by `phase3_label/label.py` - mode: **{mode}**._\n")
    if llm.offline:
        h("> No `ANTHROPIC_API_KEY` set: labels below are deterministic stubs "
          "from cluster keywords. Re-run with a key for real LLM labels; the "
          "call count and architecture are identical.\n")

    # ----- label each cluster (1 call each) --------------------------------
    sys_label = ("You label clusters of customer banking-support queries. "
                 "Given representative queries from ONE cluster, return a short "
                 "issue label, a one-sentence description, a severity, and "
                 "whether it needs escalation (fraud, loss of access, money "
                 "missing => high/escalate).")
    rows = []
    for cid in sorted(df["cluster"].unique()):
        idxs = df.index[df["cluster"] == cid].to_numpy()
        reps = representatives(texts, emb, idxs)
        terms = top_terms([texts[i] for i in idxs])
        user = ("Representative queries:\n- " + "\n- ".join(reps) +
                f"\n\nCluster size: {len(idxs)} queries.")
        hint = {"label": terms.title() or f"Cluster {cid}",
                "description": f"Queries about {terms}.",
                "severity": "medium", "needs_escalation": False}
        out = llm.json(sys_label, user, LABEL_SCHEMA, hint=hint,
                       label=f"label_c{cid}")
        rows.append({"cluster": cid, "size": len(idxs), "label": out["label"],
                     "description": out["description"],
                     "severity": out["severity"],
                     "needs_escalation": bool(out["needs_escalation"]),
                     "top_terms": terms})
    clusters = pd.DataFrame(rows).sort_values("size", ascending=False)
    clusters.to_csv(REPORTS / "cluster_labels.csv", index=False)

    total = int(clusters["size"].sum())
    h("## Labelled clusters (by volume)\n")
    h("| label | volume | % | severity | escalate | description |")
    h("|---|---|---|---|---|---|")
    for _, r in clusters.iterrows():
        esc = "⚠️ yes" if r["needs_escalation"] else "no"
        h(f"| {r['label']} | {r['size']} | {r['size']/total:.0%} | "
          f"{r['severity']} | {esc} | {r['description']} |")
    h("")

    # ----- weekly ops report (1 call) --------------------------------------
    table = "\n".join(
        f"- {r['label']}: {r['size']} queries ({r['size']/total:.0%}), "
        f"severity {r['severity']}"
        f"{', ESCALATE' if r['needs_escalation'] else ''}"
        for _, r in clusters.iterrows())
    sys_report = ("You are a support operations analyst. Write a concise weekly "
                  "ops report for a banking support team from labelled issue "
                  "clusters and their volumes. Sections: (1) Top issues by "
                  "volume, (2) Needs escalation, (3) Two concrete "
                  "recommendations. Keep it under 250 words.")
    user_report = f"This week's clusters ({total} queries total):\n{table}"
    top3 = clusters.head(3)
    esc = clusters[clusters["needs_escalation"]]
    hint = (
        f"**Top issues by volume:** " +
        "; ".join(f"{r['label']} ({r['size']})" for _, r in top3.iterrows()) +
        ".\n\n**Needs escalation:** " +
        ("; ".join(esc["label"]) if len(esc) else "none flagged") +
        ".\n\n**Recommendations:** (1) Staff the top issue category. "
        "(2) Add a self-serve FAQ for the most common request.")
    report = llm.text(sys_report, user_report, hint=hint, label="ops_report")
    h("## Weekly ops report\n")
    h(report)
    h("")
    (REPORTS / "ops_report.md").write_text(report + "\n")

    # ----- LLM accounting --------------------------------------------------
    u = llm.usage
    h("## LLM usage & cost\n")
    h(f"- **Total LLM calls: {u.calls}** ({len(clusters)} cluster labels + 1 "
      f"ops report){' [cache hits: %d]' % u.cache_hits if u.cache_hits else ''}.")
    if llm.offline:
        h(f"- Offline stub: no tokens billed. A live run is **{u.calls} calls** "
          "total; projected cost is tiny - see README (~$0.01-0.05 on "
          "claude-opus-4-8; ~5x less on claude-haiku-4-5).")
    else:
        h(f"- Tokens: {u.input_tokens:,} in / {u.output_tokens:,} out on "
          f"`{u.model}`.")
        h(f"- **Estimated cost: ${u.cost_usd:.4f}** on `{u.model}`.")
    h("")

    (REPORTS / "report.md").write_text("\n".join(md) + "\n")
    print(f"\nWrote {REPORTS/'report.md'}. calls={u.calls} cost=${u.cost_usd:.4f}")


if __name__ == "__main__":
    main()
